<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>WorkerRobotMod_REMASTER</AssemblyName>
    <LangVersion>10.0</LangVersion>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\core\BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.Common">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\core\BepInEx.Unity.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.HarmonySupport">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\core\Il2CppInterop.HarmonySupport.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\interop\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\interop\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\interop\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\interop\UnityEngine.UIModule.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\interop\UnityEngine.UI.dll</HintPath>
        <Private>false</Private>
      </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>G:\Steam\steamapps\common\Cliff Empire\REMASTER\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
